apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sharycar-feedback-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharycar-feedback
  template:
    metadata:
      labels:
        app: sharycar-feedback
    spec:
      containers:
      - name: sharycar-feedback-container
        image: jkrajnc11/sharycar-microservice-feedback
        ports:
        - containerPort: 8080

        
---
apiVersion: v1
kind: Service
metadata:
  name: sharycar-feedback-lb
spec:
  type: LoadBalancer
  selector:
    app: sharycar-feedback
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
